version: '3.5'

services:
  cookbook-db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: cookbook
      POSTGRES_PASSWORD: localdb
      POSTGRES_DB: cookbook
    volumes:
      - cookbook-db-volume:/var/lib/postgresql/data
    networks:
      - cookbook-network

  cookbook-adminer:
    image: adminer
    restart: always
    ports:
      - 8888:8080
    networks:
      - cookbook-network

volumes:
  cookbook-db-volume:
    name: cookbook-db-volume

networks:
  cookbook-network:
    name: cookbook-network