DELETE FROM ingredients where ingredient_group_id in (SELECT id FROM ingredient_groups where recipe_id in (SELECT id FROM recipes where deleted = true));
DELETE FROM ingredients where deleted = true;
ALTER TABLE ingredients DROP COLUMN deleted;
DELETE FROM ingredient_groups where recipe_id in (SELECT id FROM recipes where deleted = true);
DELETE FROM ingredient_groups where deleted = true;
ALTER TABLE ingredient_groups DROP COLUMN deleted;
DELETE FROM steps where deleted = true;
ALTER TABLE steps DROP COLUMN deleted;
UPDATE shopping_list_items r set recipe_id = null where recipe_id in (SELECT id FROM recipes where deleted = true);
DELETE FROM day_plan_recipe_ids WHERE recipe_id in (SELECT id FROM recipes where deleted = true);
DELETE FROM recipe_tags where recipe_id in (SELECT id FROM recipes where deleted = true);
DELETE FROM recipes where deleted = true;
ALTER TABLE recipes DROP COLUMN deleted;
UPDATE recipes r set category_id = null where category_id in (SELECT id FROM categories where deleted = true);
DELETE FROM categories where deleted = true;
ALTER TABLE categories DROP COLUMN deleted;
DELETE FROM day_plan_recipe_ids WHERE day_plan_id in (SELECT id FROM day_plans where deleted = true);
DELETE FROM day_plans where deleted = true;
ALTER TABLE day_plans DROP COLUMN deleted;
DELETE FROM shopping_list_items where shopping_list_id in (SELECT id FROM shopping_lists where deleted = true);
DELETE FROM shopping_list_items where deleted = true;
ALTER TABLE shopping_list_items DROP COLUMN deleted;
DELETE FROM shopping_lists where deleted = true;
ALTER TABLE shopping_lists DROP COLUMN deleted;