spring:
  autoconfigure.exclude: org.springframework.boot.autoconfigure.security.SecurityAutoConfiguration
  datasource:
    url: jdbc:postgresql://130.61.97.249:5433/kitchenassistant
    username: kitchenassistant
    password: localdb
  jpa:
    show-sql: true
  mail:
    enable: false
    host:
    port:
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
security:
  jwt:
    secret: dupa