spring:
  autoconfigure.exclude: org.springframework.boot.autoconfigure.security.SecurityAutoConfiguration
  datasource:
    url: jdbc:postgresql://localhost:5432/kitchenassistant
    username: kitchenassistant
    password: localdb
  jpa:
    show-sql: true
security:
  jwt:
    secret: dupa
ftp:
  host: localhost
  port: 21
  user: kitchenassistant
  password: kitchenassistant