spring:
  autoconfigure.exclude: org.springframework.boot.autoconfigure.security.SecurityAutoConfiguration
  datasource:
    url: jdbc:postgresql://130.61.97.249:5433/kitchenassistant
    username: kitchenassistant
    password: localdb
  jpa:
    show-sql: true
security:
  jwt:
    secret: dupa